# https://github.com/zeke/semantic-pull-requests#configuration

# Always validate the PR title AND all the commits
titleAndCommits: true

# Allow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowMergeCommits: true

# Allow use of Revert commits (eg on github: "Revert "feat: ride unicorns"")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowRevertCommits: true

# Scopes matching the ones defined in .commitlintrc.js file
scopes:
  - 'avatar'
  - 'badge'
  - 'button'
  - 'button-group'
  - 'button-toggle'
  - 'checkbox'
  - 'dropdown'
  - 'file-input'
  - 'file-uploader'
  - 'input'
  - 'loader-linear'
  - 'loader-spinner'
  - 'modal'
  - 'panel'
  - 'pill'
  - 'radio'
  - 'range-slider'
  - 'select'
  - 'skeleton'
  - 'table'
  - 'textarea'
  - 'toggle'
  - 'pagination'
  - 'transitions'
  - 'tooltip'
  - 'outer-html'
  - 'click-away'
  - 'intersect'
  - 'deps'
  - 'deps-dev'
