<template>
    <img :src="src" :alt="icon + ' icon'" :class="classes">
    <div v-html="require(src)" />
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue';

export default defineComponent({
    name: 'UIIcon',

    props: {
        solid: {
            type: Boolean,
            default: false
        },

        size: {
            type: Number,
            default: 5
        },

        academicCap: Boolean,
        adjustments: Boolean,
        annotation: Boolean,
        archive: Boolean,
        arrowCircleDown: Boolean,
        arrowCircleLeft: Boolean,
        arrowCircleRight: Boolean,
        arrowCircleUp: Boolean,
        arrowDown: Boolean,
        arrowLeft: Boolean,
        arrowNarrowDown: Boolean,
        arrowNarrowLeft: Boolean,
        arrowNarrowRight: Boolean,
        arrowNarrowUp: Boolean,
        arrowRight: Boolean,
        arrowUp: Boolean,
        arrowsExpand: Boolean,
        atSymbol: Boolean,
        backspace: Boolean,
        badgeCheck: Boolean,
        ban: Boolean,
        beaker: Boolean,
        bell: Boolean,
        bookOpen: Boolean,
        bookmark: Boolean,
        bookmarkAlt: Boolean,
        briefcase: Boolean,
        cake: Boolean,
        calculator: Boolean,
        calendar: Boolean,
        camera: Boolean,
        cash: Boolean,
        chartBar: Boolean,
        chartPie: Boolean,
        chartSquareBar: Boolean,
        chat: Boolean,
        chatAlt: Boolean,
        chatAlt2: Boolean,
        check: Boolean,
        checkCircle: Boolean,
        chevronDoubleDown: Boolean,
        chevronDoubleLeft: Boolean,
        chevronDoubleRight: Boolean,
        chevronDoubleUp: Boolean,
        chevronDown: Boolean,
        chevronLeft: Boolean,
        chevronRight: Boolean,
        chevronUp: Boolean,
        chip: Boolean,
        clipboard: Boolean,
        clipboardCheck: Boolean,
        clipboardCopy: Boolean,
        clipboardList: Boolean,
        clock: Boolean,
        cloud: Boolean,
        cloudDownload: Boolean,
        cloudUpload: Boolean,
        code: Boolean,
        cog: Boolean,
        collection: Boolean,
        colorSwatch: Boolean,
        creditCard: Boolean,
        cube: Boolean,
        cubeTransparent: Boolean,
        currencyBangladeshi: Boolean,
        currencyDollar: Boolean,
        currencyEuro: Boolean,
        currencyPound: Boolean,
        currencyRupee: Boolean,
        currencyYen: Boolean,
        cursorClick: Boolean,
        database: Boolean,
        desktopComputer: Boolean,
        deviceMobile: Boolean,
        deviceTablet: Boolean,
        document: Boolean,
        documentAdd: Boolean,
        documentDownload: Boolean,
        documentDuplicate: Boolean,
        documentRemove: Boolean,
        documentReport: Boolean,
        documentSearch: Boolean,
        documentText: Boolean,
        dotsCircleHorizontal: Boolean,
        dotsHorizontal: Boolean,
        dotsVertical: Boolean,
        download: Boolean,
        duplicate: Boolean,
        emojiHappy: Boolean,
        emojiSad: Boolean,
        exclamation: Boolean,
        exclamationCircle: Boolean,
        externalLink: Boolean,
        eye: Boolean,
        eyeOff: Boolean,
        fastForward: Boolean,
        film: Boolean,
        filter: Boolean,
        fingerPrint: Boolean,
        fire: Boolean,
        flag: Boolean,
        folder: Boolean,
        folderAdd: Boolean,
        folderDownload: Boolean,
        folderOpen: Boolean,
        folderRemove: Boolean,
        gift: Boolean,
        globe: Boolean,
        globeAlt: Boolean,
        hand: Boolean,
        hashtag: Boolean,
        heart: Boolean,
        home: Boolean,
        identification: Boolean,
        inbox: Boolean,
        inboxIn: Boolean,
        informationCircle: Boolean,
        key: Boolean,
        library: Boolean,
        lightBulb: Boolean,
        lightningBolt: Boolean,
        link: Boolean,
        locationMarker: Boolean,
        lockClosed: Boolean,
        lockOpen: Boolean,
        login: Boolean,
        logout: Boolean,
        mail: Boolean,
        mailOpen: Boolean,
        map: Boolean,
        menu: Boolean,
        menuAlt1: Boolean,
        menuAlt2: Boolean,
        menuAlt3: Boolean,
        menuAlt4: Boolean,
        microphone: Boolean,
        minus: Boolean,
        minusCircle: Boolean,
        minusSm: Boolean,
        moon: Boolean,
        musicNote: Boolean,
        newspaper: Boolean,
        officeBuilding: Boolean,
        paperAirplane: Boolean,
        paperClip: Boolean,
        pause: Boolean,
        pencil: Boolean,
        pencilAlt: Boolean,
        phone: Boolean,
        phoneIncoming: Boolean,
        phoneMissedCall: Boolean,
        phoneOutgoing: Boolean,
        photograph: Boolean,
        play: Boolean,
        plus: Boolean,
        plusCircle: Boolean,
        plusSm: Boolean,
        presentationChartBar: Boolean,
        presentationChartLine: Boolean,
        printer: Boolean,
        puzzle: Boolean,
        qrcode: Boolean,
        questionMarkCircle: Boolean,
        receiptRefund: Boolean,
        receiptTax: Boolean,
        refresh: Boolean,
        reply: Boolean,
        rewind: Boolean,
        rss: Boolean,
        save: Boolean,
        saveAs: Boolean,
        scale: Boolean,
        scissors: Boolean,
        search: Boolean,
        searchCircle: Boolean,
        selector: Boolean,
        server: Boolean,
        share: Boolean,
        shieldCheck: Boolean,
        shieldExclamation: Boolean,
        shoppingBag: Boolean,
        shoppingCart: Boolean,
        sortAscending: Boolean,
        sortDescending: Boolean,
        sparkles: Boolean,
        speakerphone: Boolean,
        star: Boolean,
        statusOffline: Boolean,
        statusOnline: Boolean,
        stop: Boolean,
        sun: Boolean,
        support: Boolean,
        switchHorizontal: Boolean,
        switchVertical: Boolean,
        table: Boolean,
        tag: Boolean,
        template: Boolean,
        terminal: Boolean,
        thumbDown: Boolean,
        thumbUp: Boolean,
        ticket: Boolean,
        translate: Boolean,
        trash: Boolean,
        trendingDown: Boolean,
        trendingUp: Boolean,
        truck: Boolean,
        upload: Boolean,
        user: Boolean,
        userAdd: Boolean,
        userCircle: Boolean,
        userGroup: Boolean,
        userRemove: Boolean,
        users: Boolean,
        variable: Boolean,
        videoCamera: Boolean,
        viewBoards: Boolean,
        viewGrid: Boolean,
        viewGridAdd: Boolean,
        viewList: Boolean,
        volumeOff: Boolean,
        volumeUp: Boolean,
        wifi: Boolean,
        x: Boolean,
        xCircle: Boolean,
        zoomIn: Boolean,
        zoomOut: Boolean
    },

    setup(props: any) {
        const icon = computed(() => {
            // Find the icon prop that has been used
            const name = Object.keys(props).find(key => props[key] && icons.includes(key));

            if (!name) {
                throw Error(
                    'You must use an icon attribute that matches the available heroicons: https://heroicons.com/'
                );
            }

            // Convert the camel-cased prop to kebab-case
            return name.replace(/([A-Z])/g, match => '-' + match.toLowerCase());
        });

        const type = computed(() => props.solid ? 'solid' : 'outline');
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const src = computed(() => require(`./${type.value}/${icon.value}.svg`));
        const classes = computed(() => `h-${props.size} w-${props.size}`);

        return { src, classes, icon };
    }
});

const icons = [
    'academicCap',
    'adjustments',
    'annotation',
    'archive',
    'arrowCircleDown',
    'arrowCircleLeft',
    'arrowCircleRight',
    'arrowCircleUp',
    'arrowDown',
    'arrowLeft',
    'arrowNarrowDown',
    'arrowNarrowLeft',
    'arrowNarrowRight',
    'arrowNarrowUp',
    'arrowRight',
    'arrowUp',
    'arrowsExpand',
    'atSymbol',
    'backspace',
    'badgeCheck',
    'ban',
    'beaker',
    'bell',
    'bookOpen',
    'bookmark',
    'bookmarkAlt',
    'briefcase',
    'cake',
    'calculator',
    'calendar',
    'camera',
    'cash',
    'chartBar',
    'chartPie',
    'chartSquareBar',
    'chat',
    'chatAlt',
    'chatAlt2',
    'check',
    'checkCircle',
    'chevronDoubleDown',
    'chevronDoubleLeft',
    'chevronDoubleRight',
    'chevronDoubleUp',
    'chevronDown',
    'chevronLeft',
    'chevronRight',
    'chevronUp',
    'chip',
    'clipboard',
    'clipboardCheck',
    'clipboardCopy',
    'clipboardList',
    'clock',
    'cloud',
    'cloudDownload',
    'cloudUpload',
    'code',
    'cog',
    'collection',
    'colorSwatch',
    'creditCard',
    'cube',
    'cubeTransparent',
    'currencyBangladeshi',
    'currencyDollar',
    'currencyEuro',
    'currencyPound',
    'currencyRupee',
    'currencyYen',
    'cursorClick',
    'database',
    'desktopComputer',
    'deviceMobile',
    'deviceTablet',
    'document',
    'documentAdd',
    'documentDownload',
    'documentDuplicate',
    'documentRemove',
    'documentReport',
    'documentSearch',
    'documentText',
    'dotsCircleHorizontal',
    'dotsHorizontal',
    'dotsVertical',
    'download',
    'duplicate',
    'emojiHappy',
    'emojiSad',
    'exclamation',
    'exclamationCircle',
    'externalLink',
    'eye',
    'eyeOff',
    'fastForward',
    'film',
    'filter',
    'fingerPrint',
    'fire',
    'flag',
    'folder',
    'folderAdd',
    'folderDownload',
    'folderOpen',
    'folderRemove',
    'gift',
    'globe',
    'globeAlt',
    'hand',
    'hashtag',
    'heart',
    'home',
    'identification',
    'inbox',
    'inboxIn',
    'informationCircle',
    'key',
    'library',
    'lightBulb',
    'lightningBolt',
    'link',
    'locationMarker',
    'lockClosed',
    'lockOpen',
    'login',
    'logout',
    'mail',
    'mailOpen',
    'map',
    'menu',
    'menuAlt1',
    'menuAlt2',
    'menuAlt3',
    'menuAlt4',
    'microphone',
    'minus',
    'minusCircle',
    'minusSm',
    'moon',
    'musicNote',
    'newspaper',
    'officeBuilding',
    'paperAirplane',
    'paperClip',
    'pause',
    'pencil',
    'pencilAlt',
    'phone',
    'phoneIncoming',
    'phoneMissedCall',
    'phoneOutgoing',
    'photograph',
    'play',
    'plus',
    'plusCircle',
    'plusSm',
    'presentationChartBar',
    'presentationChartLine',
    'printer',
    'puzzle',
    'qrcode',
    'questionMarkCircle',
    'receiptRefund',
    'receiptTax',
    'refresh',
    'reply',
    'rewind',
    'rss',
    'save',
    'saveAs',
    'scale',
    'scissors',
    'search',
    'searchCircle',
    'selector',
    'server',
    'share',
    'shieldCheck',
    'shieldExclamation',
    'shoppingBag',
    'shoppingCart',
    'sortAscending',
    'sortDescending',
    'sparkles',
    'speakerphone',
    'star',
    'statusOffline',
    'statusOnline',
    'stop',
    'sun',
    'support',
    'switchHorizontal',
    'switchVertical',
    'table',
    'tag',
    'template',
    'terminal',
    'thumbDown',
    'thumbUp',
    'ticket',
    'translate',
    'trash',
    'trendingDown',
    'trendingUp',
    'truck',
    'upload',
    'user',
    'userAdd',
    'userCircle',
    'userGroup',
    'userRemove',
    'users',
    'variable',
    'videoCamera',
    'viewBoards',
    'viewGrid',
    'viewGridAdd',
    'viewList',
    'volumeOff',
    'volumeUp',
    'wifi',
    'x',
    'xCircle',
    'zoomIn',
    'zoomOut'
];
</script>
