name: Auto Merge Dependency Updates

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main

jobs:
  merge-me:
    name: Merge dependencies
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
