name: Auto Merge Dependency Updates

on:
  pull_request:
    paths:
      - 'package-lock.json'
  pull_request_review:
    paths:
      - 'package-lock.json'

jobs:
  run:
    if: !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-actors: dependabot-preview[bot], dependabot[bot]
