name: Auto Merge Dependency Updates

on:
  check_suite:
    types:
      - completed
    workflows:
      - 'Test'

jobs:
  merge-me:
    name: Merge dependencies
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
