name: Lint

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.vue'
      - 'tsconfig*.json'
      - '.eslintrc.js'
      - 'package-lock.json'
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - name: ESLint
        run: node node_modules/.bin/eslint . --ext .ts,.vue
