name: Lint

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - '**/*.ts'
      - '**/*.vue'
      - 'tsconfig*.json'
      - '.eslintrc.js'
      - 'package-lock.json'
    branches:
      - main

jobs:
  lint:
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - name: ESLint
        run: node node_modules/.bin/eslint . --ext .ts,.vue
