name: Test

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - '**/*.ts'
      - '**/*.vue'
      - 'tsconfig*.json'
      - 'jest.config.js'
      - 'package-lock.json'
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm ci
      - name: Tests
        run: npm run test
