name: Type check

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.vue'
      - 'tsconfig.json'
    branches:
      - main

jobs:
  vue:
    name: Vue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: node node_modules/.bin/vuedx-typecheck src --no-pretty
